//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ClientID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string guid { get; set; }
        public string email { get; set; }
        public string Birthday { get; set; }
        public string PassportSerial { get; set; }
        public string PassportNumber { get; set; }
        public string EIN { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> InsuranceID { get; set; }
    
        public virtual AccountData AccountData { get; set; }
        public virtual Insurance Insurance { get; set; }
    }
}
