//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaborantResponsibility
    {
        public int RespID { get; set; }
        public Nullable<int> LaborantID { get; set; }
        public Nullable<int> ServiceID { get; set; }
    
        public virtual Laborant Laborant { get; set; }
        public virtual Services Services { get; set; }
    }
}
