//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersServices
    {
        public int OrderServiceID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> AccountantID { get; set; }
        public Nullable<int> AnalizatorID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> Rendered { get; set; }
        public string Status { get; set; }
    
        public virtual Accountant Accountant { get; set; }
        public virtual Analizator Analizator { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
    }
}
